import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import '../../public/sass/base/helper.scss';
import '../../public/sass/base/reset.scss';
import Header from './components/header';
import Footer from './components/footer';
import Banner from './components/banner';
import 'bootstrap/dist/css/bootstrap.min.css';
import Third_sec from './components/third_sec';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'LMS',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'${geistSans.variable} ${geistMono.variable}'}>
        <Header />
        <Banner />
        <Third_sec />
        {children}
        <Footer />
      </body>
    </html>
  );
}
